version: '3'
services:
  pg_db:
    container_name: pg_container
    image: 'postgres:latest'
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest_db
    networks:
      - myProject
networks:
  myProject:
